services:
  app_a:
    image: nginx:alpine
    container_name: app_a
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app-a.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
