services:
  app_a:
    image: nginx:alpine
    container_name: app_a
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-ab.entrypoints=websecure"
      - "traefik.http.routers.app-ab.rule=Host(`app-ab.edgardovasquez.cl`)"
      - "traefik.http.routers.app-ab.tls=true"
      - "traefik.http.routers.app-ab.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app-ab.service=app-ab-wrr@file"
      - "traefik.http.services.app-a.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
