services:
  app_z:
    image: nginx:alpine
    container_name: app_z
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-lb.entrypoints=websecure"
      - "traefik.http.routers.app-lb.rule=Host(`app-lb.edgardovasquez.cl`)"
      - "traefik.http.routers.app-lb.tls=true"
      - "traefik.http.routers.app-lb.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-lb.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true
